GDSC-DEU/2022-SolutionChallenge-UsNe

frontend/src/App.vue

- 가계부 페이지 화면 구성
- css 스타일 적용
- 사용자 입력 폼 구현
- 사용자 가계부 입력 기능 구현
- 입력 후 테이블에 리스트 보여주기 구현
#21

Feat: 가계부 입력 기능 구현

---

backend/src/main/java/com/gdsc/backend/controller/ConsumptionController.java
backend/src/main/java/com/gdsc/backend/service/ConsumptionManagementService.java

- consumptionController의 함수 반환형 ResponseEntity로 변경
- 소비 전체 볼때 List형에서 page형으로 변경
https://github.com/GDSC-DEU/2022-SolutionChallenge-UsNe/issues/20

Fix:함수반환형통일(#20)

---

backend/src/main/java/com/gdsc/backend/controller/ConsumptionController.java
backend/src/main/java/com/gdsc/backend/domain/Consumption.java
backend/src/main/java/com/gdsc/backend/dto/request/ConsumptionRequest.java
backend/src/main/java/com/gdsc/backend/dto/response/ConsumptionResponse.java
backend/src/main/java/com/gdsc/backend/service/ConsumptionManagementService.java

- dto 패키지 추가
- request response 패키지 추가
- ConsumptionController의 HttpStatus를 함수와 맞게 변경
- consumptionService의 save와 showByIndex함수의 매개변수를 Consumption에서 ConsumptionRequest로 변경
- showByIndex함수의 반환형을 ConsumptionResponse로 변경
https://github.com/GDSC-DEU/2022-SolutionChallenge-UsNe/issues/20

Fix:ConsumptionRequestResponse추가

---

frontend/src/App.vue
frontend/src/components/newModal.vue

모달창 입력값 출력
모달창 구현함수 구조 변경
모달창 description 구조 추가 
모달창 date 입력 구조 추가
모달창 tag 버튼 radio로 변경
가계부 in/out -> amount 로 변경 
https://github.com/GDSC-DEU/2022-SolutionChallenge-UsNe/issues/21

Fect: 모달창 입력값 출력하기, Fix: 모달창 구조, 모달창 구현 방법

---

frontend/src/App.vue

lists not defined error 해결
#21

Fix: lists not defined error 해결

---

frontend/package-lock.json
frontend/package.json
frontend/src/App.vue
frontend/src/components/newModal.vue

countTotal함수를 정의하여 가계부 total 계산
#21

Feat: 가계부 total값 계산해서 출력

---

backend/src/main/java/com/gdsc/backend/domain/Consumption.java
backend/src/main/java/com/gdsc/backend/domain/ConsumptionGoal.java
backend/src/main/java/com/gdsc/backend/domain/GroupList.java
backend/src/main/java/com/gdsc/backend/domain/Notice.java
backend/src/main/java/com/gdsc/backend/domain/Question.java

ConsumptionGoal
GroupList
Group
Notice
Question

fix: swagger

---

backend/build.gradle
backend/src/main/java/com/gdsc/backend/controller/UserSignController.java
backend/src/main/java/com/gdsc/backend/domain/GroupList.java
backend/src/main/java/com/gdsc/backend/domain/Notice.java
backend/src/main/java/com/gdsc/backend/domain/Question.java
backend/src/main/java/com/gdsc/backend/domain/User.java
backend/src/main/java/com/gdsc/backend/dto/request/UserRequest.java
backend/src/main/java/com/gdsc/backend/repository/UserRepository.java
backend/src/main/java/com/gdsc/backend/service/UserService.java

[수정 필요 부분]
- 비번 특수 문자 제한
- 비번저장 제한
- swagger 작성

Feat: SignUp

---

frontend/src/App.vue
frontend/src/components/newModal.vue

가계부 입력 항목 비어있을 때 경고메세지 출력
태그 추가 대신 기타 항목으로 대체
#21 
#22

Feat: 가계부 경고메세지, 기타 항목 만들기 Style: button hover css

---

backend/src/main/java/com/gdsc/backend/annotation/LoginUser.java
backend/src/main/java/com/gdsc/backend/controller/LoginController.java
backend/src/main/java/com/gdsc/backend/controller/UserSignController.java
backend/src/main/java/com/gdsc/backend/domain/User.java
backend/src/main/java/com/gdsc/backend/dto/request/ConsumptionRequest.java
backend/src/main/java/com/gdsc/backend/dto/request/LoginRequest.java
backend/src/main/java/com/gdsc/backend/dto/response/UserResponse.java
backend/src/main/java/com/gdsc/backend/exception/LoginFailException.java
backend/src/main/java/com/gdsc/backend/service/LoginService.java
backend/src/main/java/com/gdsc/backend/service/UserService.java
backend/src/main/java/com/gdsc/backend/service/UserSession.java

- login 기능 추가
- loginRequest의 userId를 이용하여 데이터베이스에서 user를 찾고 그 user가 가지고있는 password와 loginRequest의 password가 같은지 확인한 후 로그인
- 로그인 시 세션 생성
- logout 기능 추가
- session 기능 추가
- swagger 추가
https://github.com/GDSC-DEU/2022-SolutionChallenge-UsNe/issues/14

Feat: login & logout

---

frontend/package-lock.json
frontend/package.json
frontend/src/main.js
frontend/src/pages/accountbook/index.vue
frontend/src/pages/community/index.vue
frontend/src/pages/data/index.vue
frontend/src/pages/index.vue
frontend/src/pages/login/index.vue
frontend/src/pages/preferences/index.vue
frontend/src/pages/signup/index.vue
frontend/src/router/index.js

Router를 이용하여 가계부, 로그인, 회원가입, 통계, 커뮤니티, 환경설정 페이지 생성
로그인 css구성
#13

Feat: Router 설정 및 페이지 생성, Style: 로그인 css 구성

---

frontend/src/App.vue
frontend/src/pages/accountbook/index.vue
frontend/src/pages/login/index.vue
frontend/src/pages/signup/index.vue

Feat: navbar 생성, Style: 회원가입 css 구성

---

frontend/src/pages/login/index.vue
frontend/src/pages/signup/index.vue

Fix: 회원가입 css 수정

---

backend/src/main/java/com/gdsc/backend/controller/ConsumptionController.java
backend/src/main/java/com/gdsc/backend/controller/LoginController.java
backend/src/main/java/com/gdsc/backend/domain/User.java
backend/src/main/java/com/gdsc/backend/exception/ConsumptionDeleteFailException.java
backend/src/main/java/com/gdsc/backend/exception/ConsumptionUpdateFailException.java
backend/src/main/java/com/gdsc/backend/repository/ConsumptionRepository.java
backend/src/main/java/com/gdsc/backend/service/ConsumptionManagementService.java
backend/src/main/java/com/gdsc/backend/service/LoginService.java
backend/src/main/java/com/gdsc/backend/service/UserService.java

- ConsumptionController의 showConsumptionList함수, showConsumptionByIndex함수, updateConsumption함수,  deleteConsumption함수의 매개변수에 세션을 받아오는 HttpSession클래스의 httpSession변수 추가
- showConsumptionList함수에서 httpSession을 이용하여 로그인한 유저가 누군지 파악하고 로그인한 유저가 등록한 소비만 전체적으로 보여주도록 수정
- showConsumptionByIndex함수에서 httpSession을 이용하여 로그인한 유저가 누군지 파악하고 로그인한 유저가 등록한 소비만 선택하여 보여줄 수 있도록 수정
- updateConsumption함수에서 httpSession을 이용하여 로그인한 유저가 누군지 파악하고 로그인한 유저가 등록한 소비만 update할 수 있도록 수정
- deleteConsumption함수에서 httpSession을 이용하여 로그인한 유저가 누군지 파악하고 로그인한 유저가 등록한 소비만 삭제할 수 있도록 수정
- 세션을 이용하여 로그인 유저의 아이디를 저장하는 방식을 수정
https://github.com/GDSC-DEU/2022-SolutionChallenge-UsNe/issues/20

Feat: 사용자를 식별하여 소비기능 작동

---

backend/src/main/java/com/gdsc/backend/controller/LoginController.java

- 로그아웃의 세션 name이 변경이 안되어있어서 오류가 발생하여 세션 name을 변경
https://github.com/GDSC-DEU/2022-SolutionChallenge-UsNe/issues/14

Fix: logout 수정

---

backend/src/main/java/com/gdsc/backend/config/WebConfig.java
backend/src/main/java/com/gdsc/backend/controller/ConsumptionController.java

- 서버 ip에서 오는 요청은 어느 url이든 CORS를 적용해주도록 설정

Feat: cors

---

backend/src/main/java/com/gdsc/backend/controller/UserSignController.java
backend/src/main/java/com/gdsc/backend/dto/request/UserRequest.java
backend/src/main/java/com/gdsc/backend/repository/UserRepository.java
backend/src/main/java/com/gdsc/backend/service/UserService.java

[수정 부분]
- 아이디, 전화번호 중복체크 수정
-> 함수 수정(가독성)
- 아이디 및 비밀번호 길이 제한 수정
- 이름, 전화번호 공백 제한 수정
- 생일 패턴 제한 수정
[추가 기능]
- 아이디 제한 생성
- 영어, 숫자 혼합 (1~10자 / 1회 이상 사용)
- 비밀번호 제한 생성
- 영어, 숫자, 특수문자 (\~!@#$%^&*) 혼합 (8~20자, 1회 이상 사용, 공란X)
- 숫자 및 문자 3개 이상 중복 금지
#12

Feat: 회원가입(아이디 및 비밀번호 제한 기능)

---

backend/src/main/java/com/gdsc/backend/dto/request/UserRequest.java

[수정 부분]
- 아이디 제한 생성
- 영어, 숫자 혼합 (1~10자 / 1회 이상 사용) -> 영어 숫자 각각 1회 이상 사용 (1~10자 / 1회 이상 사용)
- 10자 이하 가능 -> 15자 이하 가능
#12

fix: SignUp

---

frontend/src/App.vue
frontend/src/api/index.js
frontend/src/pages/login/index.vue
frontend/src/pages/signup/index.vue

회원가입 api 연결, 로그인 api 연결
#13 
#11

Feat: 회원가입, 로그인 api 연결

---

frontend/src/api/index.js
frontend/src/components/AccountTable.vue
frontend/src/pages/index.vue
frontend/src/pages/login/index.vue

로그인 후 가계부 창 이동
home 페이지에 login, signup 버튼 추가
화면 렌더링 후 전체소비 가져오기
#21 
#13 
#11

Feat: 로그인 후 가계부 창 이동, 전체소비 불러오기

---

frontend/src/api/index.js
frontend/src/components/AccountTable.vue

Feat: 가게부 소비삭제

---

backend/src/main/java/com/gdsc/backend/controller/ConsumptionGoalController.java
backend/src/main/java/com/gdsc/backend/dto/request/ConsumptionGoalRequest.java
backend/src/main/java/com/gdsc/backend/repository/ConsumptionGoalRepository.java
backend/src/main/java/com/gdsc/backend/service/ConsumptionGoalService.java

- 목표소비에 관한 controller,repository,service 추가
- 목표소비 entity를 수정( 하나의 태그 저장 -> 여러태그를 저장)
- 로그인한 유저의 목표소비를 저장하는 함수 추가
https://github.com/GDSC-DEU/2022-SolutionChallenge-UsNe/issues/28

Feat: CreateConsumptionGoal

---

backend/src/main/java/com/gdsc/backend/controller/ConsumptionGoalController.java
backend/src/main/java/com/gdsc/backend/domain/ConsumptionGoal.java
backend/src/main/java/com/gdsc/backend/dto/response/ConsumptionGoalResponse.java
backend/src/main/java/com/gdsc/backend/exception/ConsumptionGoalCreateFailException.java
backend/src/main/java/com/gdsc/backend/exception/ConsumptionGoalGetFailException.java
backend/src/main/java/com/gdsc/backend/repository/ConsumptionGoalRepository.java
backend/src/main/java/com/gdsc/backend/repository/ConsumptionRepository.java
backend/src/main/java/com/gdsc/backend/service/ConsumptionGoalService.java
backend/src/main/java/com/gdsc/backend/service/ConsumptionManagementService.java

- 로그인한 유저의 목표소비를 조회, 수정하는 함수 추가
- 이번달 소비를 태그별로 합계하는 함수추가
https://github.com/GDSC-DEU/2022-SolutionChallenge-UsNe/issues/28

feat: getConsumptionGoal & updateConsumptionGoal

---

frontend/src/api/index.js
frontend/src/components/AccountTable.vue
frontend/src/components/SearchBar.vue
frontend/src/components/accountModal.vue
frontend/src/pages/accountbook/index.vue
frontend/src/pages/login/index.vue

목표소비 페이지 구성
모달창 열고 닫기 구현
모달창 페이지 구성
가계부 목표 태그 그래프 구성
한달 예산 설정 기능 추가
태그별 목표소비 입력 기능
총 지출 출력 기능
#35

Feat: 목표소비 페이지 구성, 기능 추가

---

frontend/src/components/AccountTable.vue
frontend/src/components/accountModal.vue

Fix: 목표금액 post error 해결

---

backend/src/main/java/com/gdsc/backend/controller/GroupController.java
backend/src/main/java/com/gdsc/backend/domain/GroupList.java
backend/src/main/java/com/gdsc/backend/dto/request/GroupRequest.java
backend/src/main/java/com/gdsc/backend/repository/GroupRepository.java
backend/src/main/java/com/gdsc/backend/service/GroupListService.java

- 그룹 생성,조회,수정,삭제하는 기능 추가
- 그룹을 만든 사람을 저장하도록 group엔티티 수정
- 그룹 수정,삭제는 그룹을 만든 사람만 가능하도록 기능 추가
https://github.com/GDSC-DEU/2022-SolutionChallenge-UsNe/issues/16

feat: group

---

frontend/src/api/index.js
frontend/src/components/AccountTable.vue
frontend/src/components/SearchBar.vue
frontend/src/pages/login/index.vue

로그인 : 아이디, 비밀번호 조건 넣기
검색기능 api연결
소비 검색 기능 구현
#32

Feat: 로그인 조건 넣기, 검색기능 api연결, 검색기능 구현

---

frontend/src/api/index.js
frontend/src/components/AccountTable.vue
frontend/src/components/accountModal.vue
frontend/src/pages/accountbook/index.vue
frontend/src/pages/community/index.vue

Style: community 구조, Fix: api 재복구

---

frontend/src/api/index.js
frontend/src/components/accountModal.vue
frontend/src/pages/accountbook/index.vue

목표 금액에 대한 소비 %로 표시
목표 소비 수정, 수정 후 데이터 표시
#35 #29

Feat: 목표 금액 데이터 화면 출력, 목표소비 수정

---

frontend/src/components/GoalTable.vue
frontend/src/pages/friend/index.vue
frontend/src/pages/group/index.vue

Feat: 그룹페이지에 목표소비 불러오기

---

frontend/src/api/index.js
frontend/src/pages/community/index.vue

- 그룹 생성 기능 구현
- 생성된 그룹 post
- 사용자 그룹 영역에 get
- 화면에 나타내기
- 그룹 개별 조회
#15

Feat: 커뮤니티 그룹 생성, 그룹 조회

---

frontend/src/api/index.js
frontend/src/components/AccountTable.vue

Fix: url 수정
